(add-load-path "./src")
(use isl.compiler.runner)
(use isl.compiler.runtime)

(define (assert-equal expected actual label)
  (unless (equal? expected actual)
    (error "assertion failed" label expected actual)))

(define (assert-runtime-error thunk label)
  (guard (e
          ((runtime-error? e) #t)
          (else
           (error "expected runtime-error" label e)))
    (thunk)
    (error "expected runtime-error but got value" label)))

;; ---- 1-A: 算術関数 ----
(assert-equal 5  (run-forms '((abs -5)))     "abs negative")
(assert-equal 3  (run-forms '((abs 3)))      "abs positive")
(assert-equal 0  (run-forms '((abs 0)))      "abs zero")
(assert-equal 3  (run-forms '((max 1 2 3)))  "max")
(assert-equal -1 (run-forms '((max -1 -2)))  "max negative")
(assert-equal 1  (run-forms '((min 1 2 3)))  "min")
(assert-equal -2 (run-forms '((min -1 -2)))  "min negative")
(assert-equal 1024 (run-forms '((expt 2 10))) "expt")
(assert-equal 1    (run-forms '((expt 3 0)))  "expt zero")
(assert-equal 3.0  (run-forms '((sqrt 9.0)))  "sqrt float")
(assert-equal 2    (run-forms '((sqrt 4)))    "sqrt exact")
(assert-equal 1    (run-forms '((rem 7 3)))   "rem positive")
(assert-equal -1   (run-forms '((rem -7 3)))  "rem negative dividend")
(assert-equal 1    (run-forms '((rem 7 -3)))  "rem negative divisor")
(assert-equal 4    (run-forms '((gcd 12 8)))  "gcd")
(assert-equal 5    (run-forms '((gcd 0 5)))   "gcd with zero")
(assert-equal 0    (run-forms '((gcd)))       "gcd no args")
(assert-equal 12   (run-forms '((lcm 4 6)))   "lcm")
(assert-equal 1    (run-forms '((lcm)))       "lcm no args")
(assert-equal 1    (run-forms '((signum 5)))  "signum positive")
(assert-equal -1   (run-forms '((signum -3))) "signum negative")
(assert-equal 0    (run-forms '((signum 0)))  "signum zero")
(assert-equal -7   (run-forms '((negate 7)))  "negate positive")
(assert-equal 4    (run-forms '((negate -4))) "negate negative")
(assert-equal 3.0  (run-forms '((float 3)))   "float")
(assert-equal 3    (run-forms '((isqrt 9)))   "isqrt perfect")
(assert-equal 3    (run-forms '((isqrt 10)))  "isqrt non-perfect")
(assert-equal 0    (run-forms '((isqrt 0)))   "isqrt zero")

;; ---- 1-B: 数値変換 ----
(assert-equal "ff"   (run-forms '((number->string 255 16)))   "number->string hex")
(assert-equal "1000" (run-forms '((number->string 8 2)))      "number->string bin")
(assert-equal "42"   (run-forms '((number->string 42)))       "number->string dec")
(assert-equal 255    (run-forms '((string->number "ff" 16)))  "string->number hex")
(assert-equal 8      (run-forms '((string->number "1000" 2))) "string->number bin")
(assert-equal 42     (run-forms '((string->number "42")))     "string->number dec")
(assert-equal '()    (run-forms '((string->number "xyz")))    "string->number fail")

;; ---- 1-C: 型述語 ----
(assert-equal #t (run-forms '((consp (cons 1 2))))          "consp pair")
(assert-equal '() (run-forms '((consp '())))                 "consp nil")
(assert-equal '() (run-forms '((consp 3)))                   "consp number")
(assert-equal #t (run-forms '((characterp #\a)))            "characterp char")
(assert-equal '() (run-forms '((characterp "a")))            "characterp string")
(assert-equal #t (run-forms '((integerp 3)))                "integerp int")
(assert-equal '() (run-forms '((integerp 3.0)))              "integerp float")
(assert-equal #t (run-forms '((floatp 1.5)))                "floatp float")
(assert-equal '() (run-forms '((floatp 1)))                  "floatp int")
(assert-equal #t (run-forms '((functionp (lambda (x) x))))  "functionp lambda")
(assert-equal '() (run-forms '((functionp 42)))              "functionp number")
(assert-equal #t (run-forms '((general-vector-p (vector 1 2)))) "general-vector-p vec")
(assert-equal '() (run-forms '((general-vector-p '(1 2))))       "general-vector-p list")
(assert-equal #t (run-forms '((general-array*-p (vector 1 2)))) "general-array*-p")

;; ---- 1-D: 三角・超越関数 ----
(assert-equal 1.0 (run-forms '((exp 0)))  "exp 0")
(assert-equal 0.0 (run-forms '((log 1)))  "log 1")
(assert-equal 0.0 (run-forms '((sin 0)))  "sin 0")
(assert-equal 1.0 (run-forms '((cos 0)))  "cos 0")
(assert-equal 0.0 (run-forms '((tan 0)))  "tan 0")
(assert-equal 0.0 (run-forms '((asin 0))) "asin 0")
(assert-equal 0.0 (run-forms '((acos 1))) "acos 1")
(assert-equal 0.0 (run-forms '((atan 0))) "atan 0")
(assert-equal (atan 1 1) (run-forms '((atan 1 1))) "atan 2-arg")

;; ---- 1-E: floor/ceiling/truncate/round 2引数版、quotient ----
(assert-equal 3  (run-forms '((floor 7 2)))     "floor 2-arg")
(assert-equal -4 (run-forms '((floor -7 2)))    "floor 2-arg negative")
(assert-equal 4  (run-forms '((ceiling 7 2)))   "ceiling 2-arg")
(assert-equal -3 (run-forms '((ceiling -7 2)))  "ceiling 2-arg negative")
(assert-equal 3  (run-forms '((truncate 7 2)))  "truncate 2-arg")
(assert-equal -3 (run-forms '((truncate -7 2))) "truncate 2-arg negative")
(assert-equal 4  (run-forms '((round 7 2)))     "round 2-arg")
(assert-equal 2  (run-forms '((round 5 2)))     "round 2-arg banker")
(assert-equal 2  (run-forms '((quotient 7 3)))  "quotient positive")
(assert-equal -2 (run-forms '((quotient -7 3))) "quotient negative")

;; ---- エラーケース ----
(assert-runtime-error (lambda () (run-forms '((abs "x"))))            "abs type error")
(assert-runtime-error (lambda () (run-forms '((max))))                "max arity")
(assert-runtime-error (lambda () (run-forms '((expt "a" 2))))         "expt type error")
(assert-runtime-error (lambda () (run-forms '((rem 1.5 2))))          "rem type error")
(assert-runtime-error (lambda () (run-forms '((quotient 1.5 2))))     "quotient type error")
(assert-runtime-error (lambda () (run-forms '((isqrt -1))))           "isqrt negative")
(assert-runtime-error (lambda () (run-forms '((number->string "x")))) "number->string type error")
(assert-runtime-error (lambda () (run-forms '((string->number 42))))  "string->number type error")

(display "runtime Phase1 smoke passed\n")
