;;; runtime/special-forms.scm
;;; isl.compiler.runtime: 特殊形式の評価（rt-eval-* と runtime-eval-special）
;;; src/isl/compiler/runtime.scm から (include ...) され、
;;; モジュール isl.compiler.runtime の本体に展開される（単独ロード不可）。

;; ---- runtime-eval-special: 特殊形式ごとの評価補助（旧 case 枝を抽出） ----
(define (handler-case-tag-match? tag cond-obj)
    (cond
     ((or (eq? tag 't) (eq? tag 'otherwise)) #t)
     (else
      (with-module isl.core
        (let ((bare (symbol-base-name tag)))
          (if (isl-condition? cond-obj)
              ;; Try direct class hierarchy match, then legacy bare-name fallback.
              (or (isl-subclassp? (isl-condition-class cond-obj) tag)
                  (and (string=? bare "error")
                       (isl-subclassp? (isl-condition-class cond-obj)
                                       (resolve-binding-symbol '<error>)))
                  (and (string=? bare "serious-condition")
                       (isl-subclassp? (isl-condition-class cond-obj)
                                       (resolve-binding-symbol '<serious-condition>)))
                  (and (string=? bare "condition")
                       (isl-subclassp? (isl-condition-class cond-obj)
                                       (resolve-binding-symbol '<condition>))))
              ;; Legacy Gauche native conditions
              (or (string=? bare "error")
                  (string=? bare "condition")
                  (string=? bare "serious-condition"))))))))

(define (rt-eval-setq op payload env state)
     (unless (list? payload)
       (runtime-raise 'invalid-ir "setq payload must be list" payload))
     (if (null? payload)
         (host->runtime-value '())
         (let loop ((xs payload) (last (host->runtime-value '())))
           (if (null? xs)
               last
               (let ((entry (car xs)))
                 (unless (and (list? entry) (= (length entry) 2) (symbol? (car entry)))
                   (runtime-raise 'invalid-ir "setq entry must be (symbol expr)" entry))
                 (let ((v (runtime-eval-expr (cadr entry) env state)))
                   (env-set! env (car entry) v)
                   (loop (cdr xs) v)))))))

(define (rt-eval-let op payload env state)
     (unless (and (list? payload) (= (length payload) 2))
       (runtime-raise 'invalid-ir "let payload must be (bindings body)" payload))
     (let* ((bindings (car payload))
            (body (cadr payload)))
       (unless (proper-list-host? bindings)
         (runtime-raise 'invalid-ir "let bindings must be list" bindings))
       ;; Evaluation order fixed: init forms are evaluated left-to-right in outer env.
       (let ((init-values '()))
         (let loop ((rest bindings))
           (unless (null? rest)
             (let ((b (car rest)))
               (let ((parsed (runtime-parse-let-binding b)))
                 (unless (let-binding? parsed)
                   (runtime-raise 'invalid-ir "let binding must be (symbol expr)" b))
                 (set! init-values
                       (cons (cons (let-binding-name parsed)
                                   (runtime-eval-maybe-ir (let-binding-init parsed) env state))
                             init-values)))
               (loop (cdr rest)))))
         (let ((let-env (make-env env)))
           (for-each (lambda (x) (env-define! let-env (car x) (cdr x)))
                     (reverse init-values))
           (runtime-eval-expr body let-env state)))))

(define (rt-eval-and op payload env state)
     (unless (list? payload)
       (runtime-raise 'invalid-ir "and payload must be expr list" payload))
     (let loop ((xs payload) (last (host->runtime-value #t)))
       (if (null? xs)
           last
           (let ((v (runtime-eval-expr (car xs) env state)))
             (if (runtime-truthy? v)
                 (loop (cdr xs) v)
                 (host->runtime-value '()))))))

(define (rt-eval-cond op payload env state)
     (unless (list? payload)
       (runtime-raise 'invalid-ir "cond payload must be clause list" payload))
     (let loop ((clauses payload))
       (if (null? clauses)
           (host->runtime-value '())
           (let ((clause (car clauses)))
             (unless (and (list? clause) (= (length clause) 2))
               (runtime-raise 'invalid-ir "cond clause must be (test body-or-#f)" clause))
             (let* ((test-v (runtime-eval-expr (car clause) env state))
                    (body-ir (cadr clause)))
               (if (runtime-truthy? test-v)
                   (if body-ir
                       (runtime-eval-expr body-ir env state)
                       test-v)
                   (loop (cdr clauses))))))))

(define (rt-eval-or op payload env state)
     (unless (list? payload)
       (runtime-raise 'invalid-ir "or payload must be expr list" payload))
    (let loop ((xs payload))
      (if (null? xs)
          (host->runtime-value '())
          (let ((v (runtime-eval-expr (car xs) env state)))
            (if (runtime-truthy? v)
                v
                (loop (cdr xs)))))))

(define (rt-eval-let* op payload env state)
     (unless (and (list? payload) (= (length payload) 2))
       (runtime-raise 'invalid-ir "let* payload must be (bindings body)" payload))
     (let* ((bindings (car payload))
            (body (cadr payload)))
       (unless (proper-list-host? bindings)
         (runtime-raise 'invalid-ir "let* bindings must be list" bindings))
       (let ((let-env (make-env env)))
         (for-each
         (lambda (b)
            (let ((parsed (runtime-parse-let-binding b)))
              (unless (let-binding? parsed)
                (runtime-raise 'invalid-ir "let* binding must be (symbol expr)" b))
              (let ((v (runtime-eval-maybe-ir (let-binding-init parsed) let-env state)))
                (env-define! let-env (let-binding-name parsed) v))))
          bindings)
         (runtime-eval-expr body let-env state))))

(define (rt-eval-setf op payload env state)
     (unless (and (list? payload) (= (length payload) 2))
       (runtime-raise 'invalid-ir "setf payload must be (place value)" payload))
     (let ((place (car payload))
           (value-expr (cadr payload)))
       (unless (and (list? place) (symbol? (car place)))
         (runtime-raise 'invalid-ir "setf place must be tagged place" place))
       (case (car place)
         ((place-vector-ref place-general-vector-ref)
          (unless (= (length place) 3)
            (runtime-raise 'invalid-ir "place-vector-ref expects vec/index" place))
          (let* ((vec-rv (runtime-eval-expr (cadr place) env state))
                 (idx-rv (runtime-eval-expr (caddr place) env state))
                 (value-rv (runtime-eval-expr value-expr env state))
                 (vec (runtime-vector vec-rv "setf vector-ref"))
                 (idx (runtime-number idx-rv "setf vector-ref")))
            (when (or (< idx 0) (>= idx (vector-length vec)))
              (runtime-raise 'index-out-of-range "setf vector-ref: index out of range" idx-rv))
            (vector-set! vec idx (runtime-value->host value-rv))
            value-rv))
         ((place-aref)
          (unless (= (length place) 3)
            (runtime-raise 'invalid-ir "place-aref expects array/index" place))
          (let* ((arr-rv (runtime-eval-expr (cadr place) env state))
                 (idx-rv (runtime-eval-expr (caddr place) env state))
                 (value-rv (runtime-eval-expr value-expr env state))
                 (arr (runtime-value->host arr-rv))
                 (idx (runtime-number idx-rv "setf aref")))
            (cond
             ((vector? arr)
              (when (or (< idx 0) (>= idx (vector-length arr)))
                (runtime-raise 'index-out-of-range "setf aref: index out of range" idx-rv))
              (vector-set! arr idx (runtime-value->host value-rv)))
             (else
              (runtime-raise 'type-error "setf aref: first argument must be an array" arr-rv)))
            value-rv))
         ((place-car)
          (unless (= (length place) 2)
            (runtime-raise 'invalid-ir "place-car expects one expr" place))
          (let* ((pair-rv (runtime-eval-expr (cadr place) env state))
                 (value-rv (runtime-eval-expr value-expr env state))
                 (pair (runtime-value->host pair-rv)))
            (unless (pair? pair)
              (runtime-raise 'type-error "setf car: argument must be a pair" pair-rv))
            (set-car! pair (runtime-value->host value-rv))
            value-rv))
         ((place-cdr)
          (unless (= (length place) 2)
            (runtime-raise 'invalid-ir "place-cdr expects one expr" place))
          (let* ((pair-rv (runtime-eval-expr (cadr place) env state))
                 (value-rv (runtime-eval-expr value-expr env state))
                 (pair (runtime-value->host pair-rv)))
            (unless (pair? pair)
              (runtime-raise 'type-error "setf cdr: argument must be a pair" pair-rv))
            (set-cdr! pair (runtime-value->host value-rv))
            value-rv))
         ((place-string-ref)
          (unless (= (length place) 3)
            (runtime-raise 'invalid-ir "place-string-ref expects string/index" place))
          (let* ((str-rv (runtime-eval-expr (cadr place) env state))
                 (idx-rv (runtime-eval-expr (caddr place) env state))
                 (value-rv (runtime-eval-expr value-expr env state))
                 (str (runtime-string str-rv "setf string-ref"))
                 (idx (runtime-number idx-rv "setf string-ref"))
                 (c (runtime-value->host value-rv)))
            (unless (char? c)
              (runtime-raise 'type-error "setf string-ref: value must be a character" value-rv))
            (when (or (< idx 0) (>= idx (string-length str)))
              (runtime-raise 'index-out-of-range "setf string-ref: index out of range" idx-rv))
            (string-set! str idx c)
            value-rv))
         (else
         (runtime-raise 'unsupported-special "unsupported setf place" place)))))

(define (rt-eval-block op payload env state)
     (unless (and (list? payload) (= (length payload) 2) (symbol? (car payload)))
       (runtime-raise 'invalid-ir "block payload must be (name body)" payload))
     (let ((name (car payload))
           (body (cadr payload)))
       (guard (e
               ((nonlocal-return? e)
                (if (eq? (nonlocal-return-name e) name)
                    (nonlocal-return-value e)
                    (raise e)))
               (else (raise e)))
         (runtime-eval-expr body env state))))

(define (rt-eval-return-from op payload env state)
     (unless (and (list? payload) (= (length payload) 2) (symbol? (car payload)))
       (runtime-raise 'invalid-ir "return-from payload must be (name value)" payload))
     (let ((name (car payload))
           (value (runtime-eval-expr (cadr payload) env state)))
       (raise (make-nonlocal-return name value))))

(define (rt-eval-catch op payload env state)
     (unless (and (list? payload) (= (length payload) 2))
       (runtime-raise 'invalid-ir "catch payload must be (tag body)" payload))
     (let ((tag (runtime-value->host (runtime-eval-expr (car payload) env state)))
           (body (cadr payload)))
       (dynamic-wind
         (lambda () (set! *runtime-catch-stack* (cons tag *runtime-catch-stack*)))
         (lambda ()
           (guard (e
                   ((throw-signal? e)
                    (if (eqv? (throw-signal-tag e) tag)
                        (throw-signal-value e)
                        (raise e)))
                   (else (raise e)))
             (runtime-eval-expr body env state)))
         (lambda () (set! *runtime-catch-stack* (cdr *runtime-catch-stack*))))))

(define (rt-eval-throw op payload env state)
     (unless (and (list? payload) (= (length payload) 2))
       (runtime-raise 'invalid-ir "throw payload must be (tag value)" payload))
     (let ((tag (runtime-value->host (runtime-eval-expr (car payload) env state)))
           (value (runtime-eval-expr (cadr payload) env state)))
       (if (runtime-catch-active? tag)
           (raise (make-throw-signal tag value))
           (runtime-raise 'control-error "No enclosing catch for throw" tag))))

(define (rt-eval-go op payload env state)
     (unless (and (list? payload) (= (length payload) 1))
       (runtime-raise 'invalid-ir "go payload must be (tag)" payload))
     (let ((tag (car payload)))
       (unless (or (symbol? tag) (integer? tag))
         (runtime-raise 'invalid-ir "go tag must be symbol or integer" tag))
       (raise (make-go-signal tag))))

(define (rt-eval-tagbody op payload env state)
     (unless (list? payload)
       (runtime-raise 'invalid-ir "tagbody payload must be item list" payload))
     (let* ((items payload)
            (labels
             (let loop ((xs items) (idx 0) (acc '()))
               (if (null? xs)
                   (reverse acc)
                   (let ((it (car xs)))
                     (if (and (list? it) (= (length it) 2) (eq? (car it) 'label))
                         (if (assoc (cadr it) acc)
                             (runtime-raise 'invalid-ir "duplicate tagbody label" (cadr it))
                             (loop (cdr xs) (+ idx 1) (cons (cons (cadr it) idx) acc)))
                         (loop (cdr xs) (+ idx 1) acc)))))))
       (let loop ((i 0))
         (if (>= i (length items))
             (host->runtime-value '())
             (let ((it (list-ref items i)))
               (if (and (list? it) (= (length it) 2) (eq? (car it) 'label))
                   (loop (+ i 1))
                   (let ((next-i
                          (guard (e
                                  ((go-signal? e)
                                   (let ((p (assoc (go-signal-tag e) labels)))
                                     (if p
                                         (cdr p)
                                         (runtime-raise 'control-error "No enclosing tagbody label for go" (go-signal-tag e)))))
                                  (else (raise e)))
                            (if (and (list? it) (= (length it) 2) (eq? (car it) 'form))
                                (runtime-eval-expr (cadr it) env state)
                                (runtime-raise 'invalid-ir "tagbody item must be label/form pair" it))
                            (+ i 1))))
                     (loop next-i))))))))

(define (rt-eval-while op payload env state)
     (unless (and (list? payload) (= (length payload) 2))
       (runtime-raise 'invalid-ir "while payload must be (test body)" payload))
     (let ((test-expr (car payload))
           (body-expr (cadr payload)))
       (let loop ((last (host->runtime-value '())))
         (if (runtime-truthy? (runtime-eval-expr test-expr env state))
             (loop (runtime-eval-expr body-expr env state))
             last))))

(define (rt-eval-with-open-file op payload env state)
     (unless (and (list? payload) (= (length payload) 4) (symbol? (car payload)))
       (runtime-raise 'invalid-ir "with-open-file payload must be (var path options body)" payload))
     (let* ((var (car payload))
            (path-expr (cadr payload))
            (options-expr (caddr payload))
            (body-expr (cadddr payload)))
       (unless (list? options-expr)
         (runtime-raise 'invalid-ir "with-open-file options must be list" options-expr))
       (let* ((path (runtime-string (runtime-eval-expr path-expr env state) "with-open-file"))
              (options
               (map (lambda (entry)
                      (unless (and (list? entry) (= (length entry) 2))
                        (runtime-raise 'invalid-ir "with-open-file option must be (key value)" entry))
                      (list (car entry)
                            (runtime-value->host (runtime-eval-expr (cadr entry) env state))))
                    options-expr))
              (direction (runtime-option-ref options "direction"))
              (if-exists (runtime-option-ref options "if-exists"))
              (if-dne (runtime-option-ref options "if-does-not-exist"))
              (direction-name
               (let ((raw (if direction direction :input)))
                 (runtime-canonical-option-key raw)))
              (port
               (if (string=? direction-name "output")
                   (cond
                    ((and if-exists if-dne)
                     (open-output-file path :if-exists if-exists :if-does-not-exist if-dne))
                    (if-exists
                     (open-output-file path :if-exists if-exists))
                    (if-dne
                     (open-output-file path :if-does-not-exist if-dne))
                    (else
                     (open-output-file path)))
                   (open-input-file path)))
              (wf-env (make-env env)))
         (env-define! wf-env var (host->runtime-value port))
         (guard (e (else
                    (close-port port)
                    (raise e)))
           (let ((r (runtime-eval-expr body-expr wf-env state)))
             (close-port port)
             r)))))

(define (rt-eval-dolist op payload env state)
     (unless (and (list? payload) (= (length payload) 4) (symbol? (car payload)))
       (runtime-raise 'invalid-ir "dolist payload must be (var list result body)" payload))
     (let* ((var (car payload))
            (list-expr (cadr payload))
            (result-expr (caddr payload))
            (body-expr (cadddr payload))
            (xs (runtime-value->host (runtime-eval-expr list-expr env state)))
            (loop-env (make-env env)))
       (unless (proper-list-host? xs)
         (runtime-raise 'type-error "dolist expects list sequence" xs))
       (env-define! loop-env var (host->runtime-value '()))
       (for-each
        (lambda (x)
          (env-set! loop-env var (host->runtime-value x))
          (runtime-eval-expr body-expr loop-env state))
        xs)
       (env-set! loop-env var (host->runtime-value '()))
       (if result-expr
           (runtime-eval-expr result-expr loop-env state)
           (host->runtime-value '()))))

(define (rt-eval-handler-case op payload env state)
     (unless (and (list? payload) (= (length payload) 2))
       (runtime-raise 'invalid-ir "handler-case payload must be (protected clauses)" payload))
     (let ((protected (car payload))
           (clauses (cadr payload)))
       (unless (list? clauses)
         (runtime-raise 'invalid-ir "handler-case clauses must be list" clauses))
       (guard (e
               ;; Nonlocal control transfers are not condition errors.
               ((or (nonlocal-return? e) (throw-signal? e) (go-signal? e))
                (raise e))
               (else
                (let loop ((cs clauses))
                  (if (null? cs)
                      (raise e)
                      (let ((c (car cs)))
                        (unless (and (list? c) (= (length c) 3) (symbol? (car c)))
                          (runtime-raise 'invalid-ir "invalid handler-case clause shape" c))
                        (let* ((raw-tag (car c))
                               ;; Resolve tag for class hierarchy lookup
                               (tag (with-module isl.core
                                      (resolve-binding-symbol raw-tag)))
                               (var  (cadr c))
                               (body (caddr c)))
                          (if (handler-case-tag-match? tag e)
                              (let ((henv (make-env env)))
                                (when var
                                  (unless (symbol? var)
                                    (runtime-raise 'invalid-ir "handler-case var must be symbol or #f" var))
                                  (env-define! henv var (host->runtime-value e)))
                                (runtime-eval-expr body henv state))
                              (loop (cdr cs)))))))))
         (runtime-eval-expr protected env state))))

(define (rt-eval-with-handler op payload env state)
     ;; payload = (handler-ir protected-ir)
     (unless (and (list? payload) (= (length payload) 2))
       (runtime-raise 'invalid-ir "with-handler payload must be (handler protected)" payload))
     (let* ((handler-ir   (car payload))
            (protected-ir (cadr payload))
            (handler-fn   (runtime-eval-expr handler-ir env state)))
       ;; *isl-handler-stack* is exported from isl.core and imported via (use isl.core).
       (parameterize ((*isl-handler-stack*
                       (cons (lambda (c)
                               (runtime-apply handler-fn
                                              (list (host->runtime-value c))
                                              state))
                             (*isl-handler-stack*))))
         (runtime-eval-expr protected-ir env state))))

(define (rt-eval-dynamic op payload env state)
     ;; payload = (sym)
     (unless (and (list? payload) (= (length payload) 1) (symbol? (car payload)))
       (runtime-raise 'invalid-ir "dynamic payload must be (sym)" payload))
     (let ((sym (car payload)))
       (let ((tbl (*dynamic-var-table*)))
         (if (hash-table-exists? tbl sym)
             (host->runtime-value (hash-table-ref tbl sym))
             (runtime-raise 'unbound-variable "dynamic variable not bound" sym)))))

(define (rt-eval-dynamic-let op payload env state)
     ;; payload = (norm-bindings body-ir)
     ;; norm-bindings = list of (var-sym norm-expr-ir)
     ;; body-ir       = (body norm-expr-ir ...)
     (unless (and (list? payload) (= (length payload) 2))
       (runtime-raise 'invalid-ir "dynamic-let payload must be (bindings body)" payload))
     (let* ((bindings   (car payload))
            (body-ir    (cadr payload))
            (tbl        (*dynamic-var-table*))
            ;; evaluate initial values
            (new-vals   (map (lambda (b)
                               (unless (and (list? b) (= (length b) 2) (symbol? (car b)))
                                 (runtime-raise 'invalid-ir "dynamic-let binding must be (sym ir)" b))
                               (cons (car b)
                                     (runtime-value->host
                                      (runtime-eval-expr (cadr b) env state))))
                             bindings))
            ;; save old values (or absence)
            (saved      (map (lambda (pair)
                               (let ((sym (car pair)))
                                 (cons sym
                                       (if (hash-table-exists? tbl sym)
                                           (cons #t (hash-table-ref tbl sym))
                                           (cons #f #f)))))
                             new-vals)))
       ;; install new values
       (for-each (lambda (pair) (hash-table-put! tbl (car pair) (cdr pair))) new-vals)
       (dynamic-wind
         (lambda () #f)
         (lambda ()
           ;; body-ir is normalize-body output: single expr or (seq ir1 ir2 ...)
           (runtime-eval-expr body-ir env state))
         (lambda ()
           ;; restore old values
           (for-each (lambda (entry)
                       (let ((sym  (car entry))
                             (had? (cadr entry))
                             (old  (cddr entry)))
                         (if had?
                             (hash-table-put! tbl sym old)
                             (hash-table-delete! tbl sym))))
                     saved)))))

(define (rt-eval-case op payload env state)
     ;; payload = (keyform-ir norm-clauses)
     ;; norm-clauses = ((keys body-ir) ... [(else body-ir)])
     (unless (and (list? payload) (= (length payload) 2))
       (runtime-raise 'invalid-ir "case payload must be (keyform clauses)" payload))
     (let* ((key (runtime-value->host (runtime-eval-expr (car payload) env state)))
            (clauses (cadr payload)))
       (let loop ((cs clauses))
         (if (null? cs)
             (host->runtime-value '())
             (let ((c (car cs)))
               (unless (and (list? c) (= (length c) 2))
                 (runtime-raise 'invalid-ir "case clause must be (keys body)" c))
               (let ((keys (car c))
                     (body-ir (cadr c)))
                 (if (eq? keys 'else)
                     (runtime-eval-expr body-ir env state)
                     (if (any (lambda (k) (eqv? key k)) keys)
                         (runtime-eval-expr body-ir env state)
                         (loop (cdr cs))))))))))

(define (rt-eval-dotimes op payload env state)
     ;; payload = (var count-ir result-ir? body-ir)
     (unless (and (list? payload) (= (length payload) 4) (symbol? (car payload)))
       (runtime-raise 'invalid-ir "dotimes payload must be (var count result? body)" payload))
     (let* ((var       (car payload))
            (count-ir  (cadr payload))
            (result-ir (caddr payload))
            (body-ir   (cadddr payload))
            (count (runtime-value->host (runtime-eval-expr count-ir env state)))
            (loop-env (make-env env)))
       (unless (and (integer? count) (>= count 0))
         (runtime-raise 'type-error "dotimes: count must be non-negative integer" count))
       (env-define! loop-env var (host->runtime-value 0))
       (let loop ((i 0))
         (when (< i count)
           (env-set! loop-env var (host->runtime-value i))
           (runtime-eval-expr body-ir loop-env state)
           (loop (+ i 1))))
       (env-set! loop-env var (host->runtime-value count))
       (if result-ir
           (runtime-eval-expr result-ir loop-env state)
           (host->runtime-value '()))))

(define (rt-eval-for op payload env state)
     ;; payload = (norm-specs end-test-ir result-ir body-ir)
     ;; norm-specs = ((sym init-ir step-ir?) ...)
     (unless (and (list? payload) (= (length payload) 4))
       (runtime-raise 'invalid-ir "for payload must be (specs end-test result body)" payload))
     (let* ((specs      (car payload))
            (end-test   (cadr payload))
            (result-ir  (caddr payload))
            (body-ir    (cadddr payload))
            (loop-env   (make-env env)))
       ;; Initialize vars
       (for-each (lambda (spec)
                   (unless (and (list? spec) (= (length spec) 3) (symbol? (car spec)))
                     (runtime-raise 'invalid-ir "for var-spec must be (sym init step?)" spec))
                   (let ((v (runtime-eval-expr (cadr spec) env state)))
                     (env-define! loop-env (car spec) v)))
                 specs)
       ;; Loop
       (let loop ()
         (if (runtime-truthy? (runtime-eval-expr end-test loop-env state))
             ;; End: evaluate result
             (runtime-eval-expr result-ir loop-env state)
             (begin
               ;; Body
               (runtime-eval-expr body-ir loop-env state)
               ;; Step: compute all new values before assigning
               (let ((new-vals
                      (map (lambda (spec)
                             (if (caddr spec)
                                 (runtime-eval-expr (caddr spec) loop-env state)
                                 (env-ref loop-env (car spec))))
                           specs)))
                 (for-each (lambda (spec val)
                              (env-set! loop-env (car spec) val))
                           specs new-vals))
               (loop))))))

(define (rt-eval-defpackage op payload env state)
     (unless (list? payload)
       (runtime-raise 'invalid-ir "defpackage payload must be list" payload))
     (host->runtime-value
      (with-module isl.core
        (eval-defpackage payload))))

(define (rt-eval-in-package op payload env state)
     (unless (and (list? payload) (= (length payload) 1))
       (runtime-raise 'invalid-ir "in-package payload must be one argument list" payload))
     (host->runtime-value
      (with-module isl.core
        (eval-in-package payload))))

(define (rt-eval-defclass op payload env state)
     (unless (and (list? payload) (= (length payload) 3) (symbol? (car payload)))
       (runtime-raise 'invalid-ir "defclass payload must be (name supers slots)" payload))
     (let* ((name (car payload))
            (super-forms (cadr payload))
            (slot-forms (caddr payload)))
       (unless (list? super-forms)
         (runtime-raise 'invalid-ir "defclass superclasses must be list" super-forms))
       (unless (list? slot-forms)
         (runtime-raise 'invalid-ir "defclass slots must be list" slot-forms))
       (let* ((supers
               (map (lambda (s)
                      (unless (symbol? s)
                        (runtime-raise 'invalid-ir "defclass superclass must be symbol" s))
                      (resolve-class-designator s env))
                    super-forms))
              ;; Phase 7-D: default to <standard-object> if supers is empty
              ;; Built-in class names must not get <standard-object> as default super.
              (supers
               (if (and (null? supers)
                        (not (memq name '(<object> <number> <integer> <float>
                                          <string> <symbol> <character> <cons>
                                          <null> <list> <basic-list> <function>
                                          <stream> <basic-array> <basic-vector>
                                          <general-vector> <standard-object>
                                          <built-in-class>))))
                   (let ((so-pair (env-find-pair env '<standard-object>)))
                     (if (and so-pair
                              (rt-value? (cdr so-pair))
                              (rt-class? (runtime-value->host (cdr so-pair))))
                         (list (runtime-value->host (cdr so-pair)))
                         supers))
                   supers))
              (own-slots
               (map (lambda (slot)
                      (unless (and (list? slot) (= (length slot) 6) (eq? (car slot) 'slot-spec))
                        (runtime-raise 'invalid-ir "invalid defclass slot-spec payload" slot))
                      (make-rt-slot-spec (cadr slot) (caddr slot) (cadddr slot) (list-ref slot 4) (list-ref slot 5)))
                    slot-forms))
              (class-obj (make-rt-class name supers own-slots)))
         (env-set! env name (host->runtime-value class-obj))
         ;; Install generated readers/writers as generic methods.
         (for-each
          (lambda (s)
            (let ((slot-name (rt-slot-name s)))
              (for-each
               (lambda (reader)
                 (let* ((generic (ensure-generic-function! reader env '(obj)))
                        (reader-fn
                         (make-fn-value
                          (make-primitive
                           reader
                           (lambda (args st)
                             (unless (= (length args) 1)
                               (runtime-raise 'arity "reader expects 1 argument" args))
                             (host->runtime-value
                              (rt-instance-slot-ref (runtime-value->host (car args)) slot-name))))))
                        (method (make-rt-method #f (list class-obj) '(obj) reader-fn)))
                   (set-rt-generic-methods! generic (cons method (rt-generic-methods generic)))))
               (rt-slot-readers s))
              (for-each
               (lambda (writer)
                 (let* ((generic (ensure-generic-function! writer env '(obj value)))
                        (writer-fn
                         (make-fn-value
                          (make-primitive
                           writer
                           (lambda (args st)
                             (unless (= (length args) 2)
                               (runtime-raise 'arity "writer expects 2 arguments" args))
                             (let ((obj (runtime-value->host (car args)))
                                   (v (runtime-value->host (cadr args))))
                               (host->runtime-value
                                (rt-instance-slot-set! obj slot-name v)))))))
                        (method (make-rt-method #f (list class-obj #f) '(obj value) writer-fn)))
                   (set-rt-generic-methods! generic (cons method (rt-generic-methods generic)))))
               (rt-slot-writers s))))
          own-slots)
         (host->runtime-value name))))

(define (rt-eval-defgeneric op payload env state)
     (unless (and (list? payload) (= (length payload) 2) (symbol? (car payload)))
       (runtime-raise 'invalid-ir "defgeneric payload must be (name params)" payload))
     (let ((name (car payload))
           (params (cadr payload)))
       (validate-params params)
       (ensure-generic-function! name env params)
       (host->runtime-value name)))

(define (rt-eval-defmethod op payload env state)
     (unless (and (list? payload) (= (length payload) 4) (symbol? (car payload)))
       (runtime-raise 'invalid-ir "defmethod payload must be (name qualifier params body)" payload))
     (let* ((name (car payload))
            (qualifier (cadr payload))
            (raw-params (caddr payload))
            (body (cadddr payload))
            (parsed (parse-method-params raw-params env))
            (plain-params (car parsed))
            (specializers (cadr parsed))
            (method-fn (make-fn-value (make-closure name plain-params body env)))
            (generic (ensure-generic-function! name env plain-params))
            (method (make-rt-method qualifier specializers plain-params method-fn)))
       (set-rt-generic-methods! generic (cons method (rt-generic-methods generic)))
       (host->runtime-value name)))

(define (rt-eval-flet-labels op payload env state)
     ;; payload = (bindings body)
     ;; bindings = list of (name params body-ir)
     (unless (and (list? payload) (= (length payload) 2) (list? (car payload)))
       (runtime-raise 'invalid-ir "flet/labels payload must be (bindings body)" payload))
     (let* ((bindings (car payload))
            (body     (cadr payload))
            (recursive? (eq? op 'labels))
            (fenv (make-env env)))
       ;; For flet, closures capture outer env; for labels, they capture fenv.
       (for-each
        (lambda (b)
          (unless (and (list? b) (= (length b) 3) (symbol? (car b)) (list? (cadr b)))
            (runtime-raise 'invalid-ir "flet/labels binding must be (name params body)" b))
          (let* ((fname  (car b))
                 (params (cadr b))
                 (fbody  (caddr b))
                 (scope  (if recursive? fenv env))
                 (closure (make-fn-value
                           (make-primitive
                            fname
                            (lambda (call-args call-state)
                              (let ((call-env (make-env scope)))
                                (bind-params! call-env params call-args)
                                (runtime-eval-expr fbody call-env call-state)))))))
            (env-define! fenv fname closure)))
        bindings)
       (runtime-eval-expr body fenv state)))

(define (rt-eval-macrolet op payload env state)
     ;; payload = (bindings body) — local macro bindings (§22)
     ;; At runtime, macrolet macros are functions that receive unevaluated args
     ;; and return expanded forms which are then evaluated.
     ;; This is a simplified implementation: macros expand at runtime.
     (unless (and (list? payload) (= (length payload) 2) (list? (car payload)))
       (runtime-raise 'invalid-ir "macrolet payload must be (bindings body)" payload))
     ;; For compiler macrolet: treat as flet since expansion happened at compile time.
     ;; If body was not expanded, just evaluate body in the outer env.
     (runtime-eval-expr (cadr payload) env state))

(define (rt-eval-the op payload env state)
     ;; payload = (class-name value-expr)
     (unless (and (list? payload) (= (length payload) 2) (symbol? (car payload)))
       (runtime-raise 'invalid-ir "the payload must be (class-name value-expr)" payload))
     (let* ((class-name (car payload))
            (value-expr (cadr payload))
            (val-rv (runtime-eval-expr value-expr env state))
            (val (runtime-value->host val-rv))
            (s (symbol->string class-name))
            (bare (if (and (> (string-length s) 0)
                           (char=? (string-ref s 0) #\<)
                           (char=? (string-ref s (- (string-length s) 1)) #\>))
                      (substring s 1 (- (string-length s) 1))
                      s))
            (ok? (cond
                  ((string=? bare "object")    #t)
                  ((string=? bare "t")         #t)
                  ((string=? bare "integer")   (and (integer? val) (exact? val)))
                  ((string=? bare "float")     (and (number? val) (inexact? val)))
                  ((string=? bare "number")    (number? val))
                  ((string=? bare "string")    (string? val))
                  ((string=? bare "symbol")    (symbol? val))
                  ((string=? bare "character") (char? val))
                  ((string=? bare "list")      (or (null? val) (pair? val)))
                  ((string=? bare "cons")      (pair? val))
                  ((string=? bare "null")      (null? val))
                  ((string=? bare "vector")    (vector? val))
                  ((string=? bare "general-vector") (vector? val))
                  ((string=? bare "function")  (and (rt-value? val-rv) (eq? (rt-tag val-rv) 'function)))
                  (else
                   (and (rt-instance? val)
                        (let* ((pair (env-find-pair env class-name))
                               (cls (and pair (runtime-value->host (cdr pair)))))
                          (and (rt-class? cls)
                               (let ((d (rt-class-distance (rt-instance-class val) cls)))
                                 (if d #t #f)))))))))
       (unless ok?
         (runtime-raise 'type-error
                        (string-append "the: value is not of class " (symbol->string class-name))
                        val-rv))
       val-rv))

(define (rt-eval-unwind-protect op payload env state)
     ;; payload = (protected-expr (cleanup-expr...))
     (unless (and (list? payload) (= (length payload) 2) (list? (cadr payload)))
       (runtime-raise 'invalid-ir "unwind-protect payload must be (protected cleanups)" payload))
     (let ((protected (car payload))
           (cleanups  (cadr payload)))
       (dynamic-wind
         (lambda () #f)
         (lambda () (runtime-eval-expr protected env state))
         (lambda ()
           (for-each (lambda (c) (runtime-eval-expr c env state)) cleanups)))))

(define (rt-eval-class op payload env state)
     (unless (and (list? payload) (= (length payload) 1) (symbol? (car payload)))
       (runtime-raise 'invalid-ir "class payload must be (sym)" payload))
     (let* ((sym (car payload))
            (pair (env-find-pair env sym)))
       (unless pair
         (runtime-raise 'invalid-ir "class: undefined class" sym))
       (let ((raw (runtime-value->host (cdr pair))))
         (unless (rt-class? raw)
           (runtime-raise 'type-error "class: not a class" sym))
         (cdr pair))))

(define (runtime-eval-special op payload env state)
  (case op
    ((setq) (rt-eval-setq op payload env state))
    ((let) (rt-eval-let op payload env state))
    ((and) (rt-eval-and op payload env state))
    ((cond) (rt-eval-cond op payload env state))
    ((or) (rt-eval-or op payload env state))
    ((let*) (rt-eval-let* op payload env state))
    ((setf) (rt-eval-setf op payload env state))
    ((block) (rt-eval-block op payload env state))
    ((return-from) (rt-eval-return-from op payload env state))
    ((catch) (rt-eval-catch op payload env state))
    ((throw) (rt-eval-throw op payload env state))
    ((go) (rt-eval-go op payload env state))
    ((tagbody) (rt-eval-tagbody op payload env state))
    ((while) (rt-eval-while op payload env state))
    ((with-open-file) (rt-eval-with-open-file op payload env state))
    ((dolist) (rt-eval-dolist op payload env state))
    ((handler-case) (rt-eval-handler-case op payload env state))
    ((with-handler) (rt-eval-with-handler op payload env state))
    ((dynamic) (rt-eval-dynamic op payload env state))
    ((dynamic-let) (rt-eval-dynamic-let op payload env state))
    ((case) (rt-eval-case op payload env state))
    ((dotimes) (rt-eval-dotimes op payload env state))
    ((for) (rt-eval-for op payload env state))
    ((defpackage) (rt-eval-defpackage op payload env state))
    ((in-package) (rt-eval-in-package op payload env state))
    ((defclass) (rt-eval-defclass op payload env state))
    ((defgeneric) (rt-eval-defgeneric op payload env state))
    ((defmethod) (rt-eval-defmethod op payload env state))
    ((flet labels) (rt-eval-flet-labels op payload env state))
    ((macrolet) (rt-eval-macrolet op payload env state))
    ((the) (rt-eval-the op payload env state))
    ((unwind-protect) (rt-eval-unwind-protect op payload env state))
    ((class) (rt-eval-class op payload env state))
    (else
     (runtime-raise 'unsupported-special "special form is not yet lowered" (list op payload)))))


;; ---- Phase 7-A: next-method support (compiler) ----
(define *rt-next-methods* (make-parameter '()))
(define *rt-current-method-args* (make-parameter '()))

(define (rt-sort-applicable methods args env)
  (let* ((scored (filter-map
                   (lambda (m)
                     (let ((score (method-applicability-score m args env)))
                       (and score (cons score m))))
                   methods))
         (sorted (sort scored (lambda (a b) (score<? (car a) (car b))))))
    (map cdr sorted)))

(define (rt-subclassp? sub super)
  (or (eq? sub super)
      (let loop ((supers (rt-class-supers sub)))
        (and (pair? supers)
             (or (rt-subclassp? (car supers) super)
                 (loop (cdr supers)))))))

(define (rt-invoke-chain procs extra-fn current-args state)
  ;; Only advertise a next method if it would succeed.
  (if (null? procs)
      (if extra-fn
          (extra-fn current-args)
          (runtime-raise 'control-error "call-next-method: no next method available" '()))
      (parameterize ((*rt-next-methods*
                      (if (or (pair? (cdr procs)) extra-fn)
                          (list (lambda (a) (rt-invoke-chain (cdr procs) extra-fn a state)))
                          '()))
                     (*rt-current-method-args* current-args))
        (runtime-apply (car procs) current-args state))))

(define (make-runtime-state . maybe-profile)
  (let ((profile (if (null? maybe-profile) 'extended (car maybe-profile)))
        (global-env (make-env #f))
        (frontend-env (make-frontend-env (if (null? maybe-profile) 'extended (car maybe-profile)))))
    (env-define! global-env 'nil (host->runtime-value '()))
    (env-define! global-env 't (host->runtime-value #t))
    (env-define! global-env 'object (host->runtime-value (make-rt-class 'object '() '())))
    (install-primitives! global-env)
    ;; ---- Phase 4-E: standard stream variables ----
    (env-define! global-env '*standard-input*  (host->runtime-value (current-input-port)))
    (env-define! global-env '*standard-output* (host->runtime-value (current-output-port)))
    (env-define! global-env '*error-output*    (host->runtime-value (current-error-port)))
    ;; ---- §18.1: standard-input/standard-output/error-output as zero-arg functions ----
    (let ((ge global-env))
      (env-define! global-env 'standard-input
        (make-fn-value (make-primitive 'standard-input
          (lambda (args state)
            (when (not (null? args))
              (runtime-raise 'arity "standard-input expects 0 arguments" args))
            (env-ref ge '*standard-input*)))))
      (env-define! global-env 'standard-output
        (make-fn-value (make-primitive 'standard-output
          (lambda (args state)
            (when (not (null? args))
              (runtime-raise 'arity "standard-output expects 0 arguments" args))
            (env-ref ge '*standard-output*)))))
      (env-define! global-env 'error-output
        (make-fn-value (make-primitive 'error-output
          (lambda (args state)
            (when (not (null? args))
              (runtime-raise 'arity "error-output expects 0 arguments" args))
            (env-ref ge '*error-output*))))))
    ;; ---- Phase 7-D: root OOP classes + built-in class hierarchy ----
    ;; Register built-in classes directly (bypassing defclass default-super logic).
    (let* ((obj  (make-rt-class '<object>          '()            '()))
           (num  (make-rt-class '<number>          (list obj)     '()))
           (int  (make-rt-class '<integer>         (list num)     '()))
           (flt  (make-rt-class '<float>           (list num)     '()))
           (chr  (make-rt-class '<character>       (list obj)     '()))
           (sym  (make-rt-class '<symbol>          (list obj)     '()))
           (fun  (make-rt-class '<function>        (list obj)     '()))
           (stm  (make-rt-class '<stream>          (list obj)     '()))
           (ba   (make-rt-class '<basic-array>     (list obj)     '()))
           (bv   (make-rt-class '<basic-vector>    (list ba)      '()))
           (gv   (make-rt-class '<general-vector>  (list bv)      '()))
           (str  (make-rt-class '<string>          (list bv)      '()))
           (bl   (make-rt-class '<basic-list>      (list obj)     '()))
           (lst  (make-rt-class '<list>            (list bl)      '()))
           (co   (make-rt-class '<cons>            (list lst)     '()))
           (nll  (make-rt-class '<null>            (list lst)     '()))
           (so   (make-rt-class '<standard-object> (list obj)     '()))
           (bic  (make-rt-class '<built-in-class>  (list obj)     '())))
      (for-each (lambda (c)
                  (env-define! global-env (rt-class-name c) (host->runtime-value c)))
                (list obj num int flt chr sym fun stm ba bv gv str bl lst co nll so bic)))
    ;; ---- Phase 7-E: initialize-object generic ----
    (let ((boot-state (vector 'runtime-state profile global-env (host->runtime-value '()) frontend-env)))
      (runtime-load-units!
       boot-state
       (frontend-compile-forms
        '((defgeneric initialize-object (obj initargs))
          (defmethod initialize-object ((obj <standard-object>) initargs) obj))
        frontend-env)))
    ;; ---- Phase 5-A: ISLISP condition class hierarchy ----
    ;; Compile defclass forms through the frontend to get proper IR, then run them.
    ;; ignore-errors is already defined via the shared frontend-env (make-initial-env).
    (let ((boot-state (vector 'runtime-state profile global-env (host->runtime-value '()) frontend-env)))
      (runtime-load-units!
       boot-state
       (frontend-compile-forms
        '((defclass <condition>                   ()                       ())
          (defclass <serious-condition>           (<condition>)            ())
          (defclass <error>                       (<serious-condition>)    ())
          (defclass <arithmetic-error>            (<error>)                ())
          (defclass <division-by-zero>            (<arithmetic-error>)     ())
          (defclass <floating-point-overflow>     (<arithmetic-error>)     ())
          (defclass <floating-point-underflow>    (<arithmetic-error>)     ())
          (defclass <control-error>               (<error>)                ())
          (defclass <parse-error>                 (<error>)                ())
          (defclass <program-error>               (<error>)                ())
          (defclass <domain-error>                (<program-error>)        ())
          (defclass <undefined-entity>            (<program-error>)        ())
          (defclass <unbound-variable>            (<undefined-entity>)     ())
          (defclass <undefined-function>          (<undefined-entity>)     ())
          (defclass <arity-error>                 (<program-error>)        ())
          (defclass <index-out-of-range>          (<program-error>)        ())
          (defclass <type-error>                  (<program-error>)        ())
          (defclass <simple-error>                (<error>)                ())
          (defclass <stream-error>                (<error>)                ())
          (defclass <end-of-stream>               (<stream-error>)         ()))
        frontend-env)))
    (vector 'runtime-state profile global-env (host->runtime-value '()) frontend-env)))

(define (state-profile state) (vector-ref state 1))
(define (state-global-env state) (vector-ref state 2))
(define (state-last-value state) (vector-ref state 3))
(define (set-state-last-value! state v) (vector-set! state 3 v))
(define (state-frontend-env state) (vector-ref state 4))

(define (runtime-eval-seq exprs env state)
  (let loop ((xs exprs) (last (host->runtime-value '())))
    (if (null? xs)
        last
        (loop (cdr xs) (runtime-eval-expr (car xs) env state)))))

(define (find-block cfg label)
  (let* ((blocks (caddr cfg))
         (p (find (lambda (b) (and (pair? b) (eq? (cadr b) label))) blocks)))
    (if p
        p
        (runtime-raise 'invalid-ir "unknown block label" label))))

(define (phi-pairs rhs)
  (if (and (pair? rhs) (eq? (car rhs) 'phi) (pair? (cdr rhs)))
      (cadr rhs)
      #f))

(define (eval-rhs rhs env state pred-label)
  (unless (and (pair? rhs) (symbol? (car rhs)))
    (runtime-raise 'invalid-ir "invalid assignment rhs" rhs))
  (case (car rhs)
    ((const)
     (if (= (length rhs) 2)
         (host->runtime-value (cadr rhs))
         (runtime-raise 'invalid-ir "const rhs expects one payload" rhs)))
    ((var)
     (if (= (length rhs) 2)
         (env-ref env (cadr rhs))
         (runtime-raise 'invalid-ir "var rhs expects one symbol" rhs)))
    ((set)
     ;; (set name value-temp): setq lowered into the CFG.  Mutate the nearest
     ;; binding (env-set! defines it when absent); the result is the value.
     (if (and (= (length rhs) 3) (symbol? (cadr rhs)) (symbol? (caddr rhs)))
         (let ((v (env-ref env (caddr rhs))))
           (env-set! env (cadr rhs) v)
           v)
         (runtime-raise 'invalid-ir "set rhs expects (name value)" rhs)))
    ((call)
     (let ((fn (env-ref env (cadr rhs)))
           (args (map (lambda (s) (env-ref env s)) (caddr rhs))))
       (runtime-apply fn args state)))
    ((lambda)
     (if (= (length rhs) 3)
         (make-fn-value (make-closure #f (cadr rhs) (caddr rhs) env))
         (runtime-raise 'invalid-ir "lambda rhs expects params/body" rhs)))
    ((special)
     (if (= (length rhs) 3)
         (runtime-eval-special (cadr rhs) (caddr rhs) env state)
         (runtime-raise 'invalid-ir "special rhs expects op/payload" rhs)))
    ((invalid-special)
     (runtime-raise 'invalid-ir "invalid special form shape in rhs" rhs))
    ((phi)
     (let ((pairs (phi-pairs rhs)))
       (unless (list? pairs)
         (runtime-raise 'invalid-ir "phi rhs expects predecessor pairs" rhs))
       (let ((selected
              (if pred-label
                  (find (lambda (x) (and (pair? x) (eq? (car x) pred-label))) pairs)
                  #f)))
         (if selected
             (env-ref env (cadr selected))
             (if (null? pairs)
                 (runtime-raise 'invalid-ir "phi has no incoming pairs" rhs)
                 (env-ref env (cadar pairs)))))))
    (else
     (runtime-raise 'invalid-ir "unknown assignment rhs op" rhs))))

(define (exec-block-instrs instrs env state pred-label)
  (for-each
   (lambda (instr)
     (unless (and (pair? instr) (eq? (car instr) 'assign) (= (length instr) 3))
       (runtime-raise 'invalid-ir "instruction must be (assign dst rhs)" instr))
     (let ((dst (cadr instr))
           (rhs (caddr instr)))
       (unless (symbol? dst)
         (runtime-raise 'invalid-ir "assign destination must be symbol" dst))
       (env-define! env dst (eval-rhs rhs env state pred-label))))
   instrs))

(define (runtime-exec-cfg cfg env state)
  (unless (and (pair? cfg) (eq? (car cfg) 'cfg) (= (length cfg) 3))
    (runtime-raise 'invalid-ir "cfg shape must be (cfg entry blocks)" cfg))
  (let ((entry (cadr cfg)))
    (let loop ((label entry) (pred #f))
      (let* ((block (find-block cfg label))
             (instrs (caddr block))
             (term (cadddr block)))
        (exec-block-instrs instrs env state pred)
        (unless (and (pair? term) (symbol? (car term)))
          (runtime-raise 'invalid-ir "block terminator is missing or invalid" block))
        (case (car term)
          ((ret)
           (if (= (length term) 2)
               (env-ref env (cadr term))
               (runtime-raise 'invalid-ir "ret expects one value symbol" term)))
          ((jmp)
           (if (= (length term) 2)
               (loop (cadr term) label)
               (runtime-raise 'invalid-ir "jmp expects target label" term)))
          ((br)
           (if (= (length term) 4)
               (let ((cond-v (env-ref env (cadr term))))
                 (if (runtime-truthy? cond-v)
                     (loop (caddr term) label)
                     (loop (cadddr term) label)))
               (runtime-raise 'invalid-ir "br expects cond then else labels" term)))
          (else
           (runtime-raise 'invalid-ir "unknown terminator op" term)))))))

(define (runtime-apply fn-val arg-vals state)
  (let ((fn (fn-from-value fn-val)))
    (cond
     ((primitive? fn)
      ((primitive-proc fn) arg-vals state))
     ((rt-generic? fn)
      (let* ((genv         (state-global-env state))
             (all-methods  (rt-generic-methods fn))
             (app-around   (rt-sort-applicable
                            (filter (lambda (m) (eq? (rt-method-qualifier m) ':around)) all-methods)
                            arg-vals genv))
             (app-before   (rt-sort-applicable
                            (filter (lambda (m) (eq? (rt-method-qualifier m) ':before)) all-methods)
                            arg-vals genv))
             (app-primary  (rt-sort-applicable
                            (filter (lambda (m) (not (rt-method-qualifier m))) all-methods)
                            arg-vals genv))
             (app-after    (reverse (rt-sort-applicable
                                     (filter (lambda (m) (eq? (rt-method-qualifier m) ':after)) all-methods)
                                     arg-vals genv))))
        (when (null? app-primary)
          (runtime-raise 'invalid-ir "No applicable primary method for generic function"
                         (rt-generic-name fn)))
        (letrec ((call-effective-primary
                  (lambda (eff-args)
                    (for-each (lambda (m)
                                (parameterize ((*rt-next-methods* '()) (*rt-current-method-args* eff-args))
                                  (runtime-apply (rt-method-fn m) eff-args state)))
                              app-before)
                    (let ((result (rt-invoke-chain (map rt-method-fn app-primary) #f eff-args state)))
                      (for-each (lambda (m)
                                  (parameterize ((*rt-next-methods* '()) (*rt-current-method-args* eff-args))
                                    (runtime-apply (rt-method-fn m) eff-args state)))
                                app-after)
                      result))))
          (if (null? app-around)
              (call-effective-primary arg-vals)
              (rt-invoke-chain (map rt-method-fn app-around) call-effective-primary arg-vals state)))))
     ((closure? fn)
      (let ((call-env (make-env (closure-env fn))))
        (bind-params! call-env (closure-params fn) arg-vals)
        (if (eq? (closure-kind fn) 'cfg)
            (runtime-exec-cfg (closure-body fn) call-env state)
            (runtime-eval-expr (closure-body fn) call-env state))))
     (else
      (runtime-raise 'type-error "invalid function object" fn)))))

(define (runtime-eval-expr ir env state)
  (unless (and (pair? ir) (symbol? (car ir)))
    (runtime-raise 'invalid-ir "IR expression must be a tagged list" ir))
  (case (car ir)
    ((const)
     (if (= (length ir) 2)
         (host->runtime-value (cadr ir))
         (runtime-raise 'invalid-ir "const expects one payload" ir)))
    ((var)
     (if (= (length ir) 2)
         (env-ref env (cadr ir))
         (runtime-raise 'invalid-ir "var expects one symbol" ir)))
    ((if)
     (if (= (length ir) 4)
         (let ((test (runtime-eval-expr (cadr ir) env state)))
           (if (runtime-truthy? test)
               (runtime-eval-expr (caddr ir) env state)
               (runtime-eval-expr (cadddr ir) env state)))
         (runtime-raise 'invalid-ir "if expects test/then/else" ir)))
    ((seq)
     (runtime-eval-seq (cdr ir) env state))
    ((lambda)
     (if (= (length ir) 3)
         (make-fn-value (make-closure #f (cadr ir) (caddr ir) env))
         (runtime-raise 'invalid-ir "lambda expects params/body" ir)))
    ((call)
     (if (>= (length ir) 2)
         (let ((fn (runtime-eval-expr (cadr ir) env state))
               (args (map (lambda (x) (runtime-eval-expr x env state)) (cddr ir))))
           (runtime-apply fn args state))
         (runtime-raise 'invalid-ir "call expects callee" ir)))
    ((effect)
     (if (= (length ir) 2)
         (runtime-eval-expr (cadr ir) env state)
         (runtime-raise 'invalid-ir "effect expects one child" ir)))
    ((special)
     (if (= (length ir) 3)
         (runtime-eval-special (cadr ir) (caddr ir) env state)
         (runtime-raise 'invalid-ir "special node expects op/payload" ir)))
    ((invalid-special)
     (runtime-raise 'invalid-ir "invalid special form shape" ir))
    (else
     (runtime-raise 'invalid-ir "unknown IR node" ir))))

