(add-load-path "./src")
(use isl.core)

(define (make-test-env)
  (make-initial-env))

(define (case-id milestone idx)
  (string-append milestone "-" (number->string idx)))

(define (fail id message . details)
  (display "FAIL ")
  (display id)
  (display ": ")
  (display message)
  (newline)
  (for-each
   (lambda (d)
     (display "  ")
     (write d)
     (newline))
   details)
  #f)

(define (run-case env milestone idx case)
  (let ((id (case-id milestone idx))
        (kind (list-ref case 0))
        (form (list-ref case 1))
        (expected (list-ref case 2)))
    (guard (e
            (else
             (if (eq? kind 'error)
                 (begin
                   (display "ok ")
                   (display id)
                   (newline)
                   #t)
                 (fail id "unexpected error" form expected e))))
      (let ((actual (eval-islisp form env)))
        (cond
         ((eq? kind 'error)
          (fail id "expected error but got value" form actual))
         ((eq? kind 'oracle)
          (display "ok ")
          (display id)
          (display " (oracle) ")
          (write actual)
          (newline)
          #t)
         ((equal? actual expected)
          (display "ok ")
          (display id)
          (newline)
          #t)
         (else
          (fail id "value mismatch" form expected actual)))))))

(define (run-milestone milestone cases)
  (let ((env (make-test-env)))
    (let loop ((xs cases) (idx 1) (ok 0) (ng 0))
      (if (null? xs)
          (begin
            (display "== ")
            (display milestone)
            (display " summary: ")
            (display ok)
            (display " passed, ")
            (display ng)
            (display " failed")
            (newline)
            (if (= ng 0) #t #f))
          (if (run-case env milestone idx (car xs))
              (loop (cdr xs) (+ idx 1) (+ ok 1) ng)
              (loop (cdr xs) (+ idx 1) ok (+ ng 1)))))))

(define (run-all milestones)
  (let loop ((xs milestones) (ok 0) (ng 0))
    (if (null? xs)
        (begin
          (display "TOTAL: ")
          (display ok)
          (display " passed milestones, ")
          (display ng)
          (display " failed milestones")
          (newline)
          (if (= ng 0) 0 1))
        (let* ((entry (car xs))
               (name (car entry))
               (cases (cadr entry))
               (result (run-milestone name cases)))
          (if result
              (loop (cdr xs) (+ ok 1) ng)
              (loop (cdr xs) ok (+ ng 1)))))))
