(add-load-path "./src")
(add-load-path "./test/conformance")
(use isl.core)
(load "milestones.scm")

;; M0 oracle compare interface:
;; - oracle evaluator: interpreter (`eval-islisp`)
;; - candidate evaluator: currently interpreter (compiler adapter will replace this)

(define (eval->result env form)
  (guard (e (else (list 'error (write-to-string e))))
    (list 'ok (eval-islisp form env))))

(define (result-equal? a b)
  (and (eq? (car a) (car b))
       (equal? (cadr a) (cadr b))))

(define (run-case oracle-env candidate-env mname idx case)
  (let ((kind (car case))
        (form (cadr case)))
    (if (eq? kind 'oracle)
        (list #t 0 0)
        (let* ((oracle-result (eval->result oracle-env form))
               (candidate-result (eval->result candidate-env form))
               (id (string-append mname "-" (number->string idx))))
          (if (result-equal? oracle-result candidate-result)
              (begin
                (display "ok ")
                (display id)
                (newline)
                (list #t 1 0))
              (begin
                (display "FAIL ")
                (display id)
                (display ": oracle/candidate mismatch")
                (newline)
                (display "  form: ")
                (write form)
                (newline)
                (display "  oracle: ")
                (write oracle-result)
                (newline)
                (display "  candidate: ")
                (write candidate-result)
                (newline)
                (list #f 0 1)))))))

(define (run-milestone oracle-env candidate-env entry ok ng)
  (let ((mname (car entry))
        (cases (cadr entry)))
    (let loop ((xs cases) (idx 1) (ok-acc ok) (ng-acc ng))
      (if (null? xs)
          (list ok-acc ng-acc)
          (let* ((r (run-case oracle-env candidate-env mname idx (car xs)))
                 (ok-inc (cadr r))
                 (ng-inc (caddr r)))
            (loop (cdr xs) (+ idx 1) (+ ok-acc ok-inc) (+ ng-acc ng-inc)))))))

(define (run-compare milestones profile)
  (let ((oracle-env (make-initial-env profile))
        (candidate-env (make-initial-env profile)))
    (let loop ((ms milestones) (ok 0) (ng 0))
      (if (null? ms)
          (begin
            (display "ORACLE-COMPARE ")
            (display profile)
            (display ": ")
            (display ok)
            (display " passed, ")
            (display ng)
            (display " failed")
            (newline)
            (if (= ng 0) 0 1))
          (let* ((totals (run-milestone oracle-env candidate-env (car ms) ok ng))
                 (ok2 (car totals))
                 (ng2 (cadr totals)))
            (loop (cdr ms) ok2 ng2))))))

(define (main argv)
  (let* ((args (cdr argv))
         (mode (if (null? args) "extended" (car args)))
         (profile (if (string-ci=? mode "strict") 'strict 'extended))
         (milestones (if (eq? profile 'strict) strict-milestones extended-milestones)))
    (run-compare milestones profile)))

(exit (main (command-line)))
